name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and push on the GitHub Container Registry
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker build -t ghcr.io/couscousorga/server-condoms:latest .
        docker push ghcr.io/couscousorga/server-condoms:latest
        docker build -t ghcr.io/couscousorga/server-condoms:${date +%s} .
        docker push ghcr.io/couscousorga/server-condoms:${date +%s}